### ISSUE TITLE
Design Tracking Solution

### ISSUE THREAD

**Issue by cjhowald** [zalando-incubator/solution-center-tracking#5]
We need to create a design document describing how this library will work and get it validated.

**Comment by cjhowald** [comment]
# Solution Center Tracking
Purpose: allow consistent business event tracking across Solution Center frontend products.

## Design

- Create a service that does the following:
  - Accepts events in [this format](https://techwiki.zalando.net/pages/viewpage.action?spaceKey=DT&title=Project+Honeypot#ProjectHoneypot-BusinessEvents)
  - Calls a solution center endpoint to persist the event

## Technical Design

- Service will be an angular 1.5 service in Typescript
- The following data does not need to be included as it will be determined from the user token:
  - User ID
  - User email
- Timestamp:
  - Calculated on the FE to avoid timing inaccuracies due to network latency (e.g. 2 events are fired in rapid succession but arrive at the BE in reverse order)
  - Optional input since the service will calculate the current time by default

**Comment by cjhowald** [comment]
@dami-gg @gregdeane Please take a look and give your input.

**Comment by gregdeane** [comment]
Looks good. What do you mean by "Optional input..." under "Timestamp?" Does this mean that a consumer of the service can pass in their own timestamp?

**Comment by cjhowald** [comment]
@gregdeane That's what we were thinking. Could be useful for testing to specify a timestamp. We expect most service consumers will not pass this parameter.

**Comment by gregdeane** [comment]
👍

**Comment by dami-gg** [comment]
It really makes sense to calculate timings in our side, I'm fine with the proposal :+1:

**Comment by cjhowald** [comment]
Closing since all Norris FE approve the design.
